import { useState, useEffect } from 'react';
import API from '../api/axios';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await API.get('/reports');
      setReports(res.data);
    } catch (err) {
      console.error('Failed to fetch reports', err);
    } finally {
      setLoading(false);
    }
  };

  const parseReportData = (data) => {
    try {
      return JSON.parse(data);
    } catch {
      return null;
    }
  };

  const renderReportData = (data) => {
    const parsed = parseReportData(data);
    if (!parsed) return <p style={{ color: 'var(--text-muted)' }}>No data available</p>;

    return (
      <div style={{ marginTop: '1rem' }}>
        {Object.entries(parsed).map(([key, value]) => (
          <div key={key} style={{ padding: '8px 0', borderBottom: '1px solid var(--border-color)' }}>
            <span style={{ color: 'var(--text-muted)', fontSize: '0.85rem', textTransform: 'capitalize' }}>
              {key.replace(/([A-Z])/g, ' $1').trim()}:
            </span>
            <span style={{ fontWeight: 600, marginLeft: '8px', color: 'var(--text-primary)', fontSize: '0.9rem' }}>
              {typeof value === 'object' ? JSON.stringify(value, null, 2) : String(value)}
            </span>
          </div>
        ))}
      </div>
    );
  };

  if (loading) return <div className="loading-spinner"><div className="spinner"></div></div>;

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>Market Reports & Insights</h1>
        <p>Data-driven analysis of investment trends and fund performance</p>
      </div>

      {selected ? (
        <div>
          <button className="btn btn-secondary btn-sm" onClick={() => setSelected(null)}
            style={{ marginBottom: '1.5rem' }}>
            ← Back to Reports
          </button>
          <div className="card">
            <div style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', marginBottom: '0.5rem' }}>
              <span className="report-type-badge">{selected.reportType?.replace('_', ' ')}</span>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                by {selected.generatedBy?.fullName} • {new Date(selected.generatedAt).toLocaleDateString()}
              </span>
            </div>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 800, marginBottom: '0.5rem' }}>{selected.title}</h2>
            <p style={{ color: 'var(--text-secondary)', lineHeight: 1.6, marginBottom: '1.5rem' }}>{selected.description}</p>

            <h3 style={{ fontWeight: 700, marginBottom: '0.5rem' }}>Report Data</h3>
            {renderReportData(selected.reportData)}
          </div>
        </div>
      ) : (
        <div className="grid-2">
          {reports.map(report => (
            <div key={report.id} className="report-card" onClick={() => setSelected(report)} style={{ cursor: 'pointer' }}>
              <span className="report-type-badge">{report.reportType?.replace('_', ' ')}</span>
              <h3 style={{ marginTop: '0.75rem', fontWeight: 700, fontSize: '1.1rem', color: 'var(--text-primary)' }}>
                {report.title}
              </h3>
              <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', marginTop: '0.5rem', lineHeight: 1.5 }}>
                {report.description}
              </p>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '0.75rem' }}>
                {report.generatedBy?.fullName} • {new Date(report.generatedAt).toLocaleDateString()}
              </div>
            </div>
          ))}
        </div>
      )}

      {reports.length === 0 && !selected && (
        <div className="empty-state">
          <h3>No reports available</h3>
          <p>Reports will appear here once generated by our data analysts</p>
        </div>
      )}
    </div>
  );
}

// Update: Add unit tests for calculation utilities
